name: weather_repository
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  open_meteo_api:
    path: ../open_meteo_api
  http: ^1.2.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializer: ^0.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  test: ^1.25.7
  coverage: ^1.9.2

flutter:
