name: weather_repository
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.7
  coverage: ^1.9.2

flutter:
