targets:
  $default:
    builders:
      source_gen|combining_builder":
        option:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serialize:
        option:
          field_rename: snake
          create_to_json: false
          checked: true